In [20]:
import jax.numpy as jnp
import numpy as np

In [21]:
a = np.array([0.1,0.4,0.5,2,3,5])
b = np.where(a<1, a, 2*a)

In [22]:
b

array([ 0.1,  0.4,  0.5,  4. ,  6. , 10. ])

In [23]:
a

array([0.1, 0.4, 0.5, 2. , 3. , 5. ])

In [24]:
c = np.linalg.norm(a)

In [25]:
c

6.198386886924694

In [26]:
a = 2

In [27]:
c = np.linalg.norm(a)

In [28]:
c

2.0

In [29]:
a = np.array([[0.1,0.4,0.5,2,3,5], [1,2,3,4,5,6]])

In [34]:
c = np.linalg.norm(a, axis=0)

In [37]:
d = np.ones(c.shape)

In [38]:
x_hi = jnp.where(c<1, 2*d, c)

In [39]:
x_hi

DeviceArray([1.0049876, 2.0396078, 3.0413814, 4.472136 , 5.8309517,
             7.81025  ], dtype=float32)